
server:
  port: 8082
  servlet:
    context-path: /api/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee?useSSL=false
    username: root
    password: mysql@237
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  banner:
    location: classpath:banner.txt
#springdoc:
#  show-actuator: true
#  swagger-ui:
#    path: department-swagger.html
management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:30000/api/v2/spans
  server:
    port: 9193

logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"




